set -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

setw -g mode-keys vi
set-option -g history-limit 10000

# # redundant if we never remapped the keys
unbind m
bind m select-pane -m
# unbind M
# bind M select-pane -M

# Enable mouse support for tmux 2.1 and later
set -g mouse off
display '~/.tmux.conf loaded -- Mouse: OFF (toggle: C-a M)'

# Toggle mouse mode on/off
bind M run "tmux display-message -p 'Mouse is #{?mouse,ON,OFF}' | grep -q 'Mouse is ON' && ( tmux set -g mouse off && tmux display-message 'Mouse: OFF' ) || ( tmux set -g mouse on && tmux display-message 'Mouse: ON' )"
